<?php
session_start(); $conn=new mysqli("localhost","root","","agroconnect"); $conn->set_charset("utf8mb4");
if(!isset($_SESSION['rol'])){header("Location: login.php");exit();}
function existe($c,$t){$t=$c->real_escape_string($t);$r=$c->query("SHOW TABLES LIKE '$t'");return $r&&$r->num_rows>0;}
$sinTabla=!existe($conn,'foro_temas'); $rol=$_SESSION['rol']; $uid=$_SESSION['id']??null; $eid=$_SESSION['empresa_id']??null;
if(!$sinTabla && isset($_POST['crear_tema'])){ $titulo=trim($_POST['titulo']); $msg=trim($_POST['mensaje']); $cat=$_POST['categoria']; $emp=($rol=='superadmin'&&!empty($_POST['empresa_id']))?intval($_POST['empresa_id']):($eid?:null); $st=$conn->prepare("INSERT INTO foro_temas (empresa_id,usuario_id,titulo,mensaje,categoria) VALUES (?,?,?,?,?)"); $st->bind_param("iisss",$emp,$uid,$titulo,$msg,$cat); $st->execute(); header("Location: foro.php"); exit(); }
$empresas=$conn->query("SELECT id,nombre FROM empresas ORDER BY nombre");
if(!$sinTabla) $temas=$conn->query("SELECT ft.*,e.nombre empresa,u.nombre usuario,(SELECT COUNT(*) FROM foro_respuestas fr WHERE fr.tema_id=ft.id) respuestas FROM foro_temas ft LEFT JOIN empresas e ON ft.empresa_id=e.id LEFT JOIN usuarios u ON ft.usuario_id=u.id ORDER BY ft.fecha_creacion DESC");
$volver=$rol=='superadmin'?'superadmin.php':($rol=='jefe'?'jefe.php':'trabajador.php');
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Foro de empresas</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body class="admin-body"><?php include __DIR__ . '/includes/topbar.php'; ?><div class="admin-container"><h2 class="admin-title">Foro de empresas y soporte</h2><?php if($sinTabla){ ?><div class="alert alert-warning">Importa <strong>actualizacion_superadmin.sql</strong> para activar el foro.</div><?php }else{ ?><div class="dashboard-grid two-columns"><div class="admin-card"><h4>Crear nuevo tema</h4><form method="POST"><?php if($rol=='superadmin'){ ?><div class="mb-3"><label class="form-label">Empresa relacionada</label><select name="empresa_id" class="form-select"><option value="">General</option><?php while($e=$empresas->fetch_assoc()){ ?><option value="<?php echo $e['id']; ?>"><?php echo htmlspecialchars($e['nombre']); ?></option><?php } ?></select></div><?php } ?><div class="mb-3"><label class="form-label">Categoría</label><select name="categoria" class="form-select"><option value="general">General</option><option value="incidencia">Incidencia</option><option value="mejora">Mejora</option><option value="soporte">Soporte</option></select></div><div class="mb-3"><label class="form-label">Título</label><input name="titulo" class="form-control" required></div><div class="mb-3"><label class="form-label">Mensaje</label><textarea name="mensaje" class="form-control" rows="4" required></textarea></div><button name="crear_tema" class="btn btn-success w-100">Publicar tema</button></form></div><div class="admin-card"><h4>Funciones del foro</h4><ul class="clean-list"><li>Preguntas entre empresas.</li><li>Consultas directas al SuperAdmin.</li><li>Historial de incidencias y soluciones.</li></ul></div></div><div class="forum-list mt-4"><?php if($temas->num_rows==0){ ?><div class="admin-card"><p class="mb-0 text-muted">Todavía no hay temas publicados.</p></div><?php } ?><?php while($t=$temas->fetch_assoc()){ ?><a class="forum-card" href="foro_tema.php?id=<?php echo $t['id']; ?>"><div><span class="forum-category"><?php echo htmlspecialchars($t['categoria']); ?></span><h4><?php echo htmlspecialchars($t['titulo']); ?></h4><p><?php echo htmlspecialchars(substr($t['mensaje'],0,160)); ?>...</p><small><?php echo htmlspecialchars($t['empresa']??'General'); ?> · <?php echo htmlspecialchars($t['usuario']??'Usuario'); ?> · <?php echo date('d/m/Y H:i',strtotime($t['fecha_creacion'])); ?></small></div><div class="forum-meta"><strong><?php echo $t['respuestas']; ?></strong><span>respuestas</span><em><?php echo htmlspecialchars($t['estado']); ?></em></div></a><?php } ?></div><?php } ?></div><?php include __DIR__ . '/includes/footer.php'; ?>
</body></html>
