<?php
session_start(); $conn=new mysqli("localhost","root","","agroconnect"); $conn->set_charset("utf8mb4");
if(!isset($_SESSION['rol'])){header("Location: login.php");exit();}
$id=intval($_GET['id']??0); $uid=$_SESSION['id']??null; $rol=$_SESSION['rol'];
if(isset($_POST['responder'])){ $msg=trim($_POST['mensaje']); $st=$conn->prepare("INSERT INTO foro_respuestas (tema_id,usuario_id,mensaje) VALUES (?,?,?)"); $st->bind_param("iis",$id,$uid,$msg); $st->execute(); $conn->query("UPDATE foro_temas SET estado='respondido',fecha_actualizacion=NOW() WHERE id=$id"); header("Location: foro_tema.php?id=$id"); exit(); }
if($rol=='superadmin' && isset($_POST['cerrar'])){ $conn->query("UPDATE foro_temas SET estado='cerrado' WHERE id=$id"); header("Location: foro_tema.php?id=$id"); exit(); }
$tema=$conn->query("SELECT ft.*,e.nombre empresa,u.nombre usuario,u.rol rol_usuario FROM foro_temas ft LEFT JOIN empresas e ON ft.empresa_id=e.id LEFT JOIN usuarios u ON ft.usuario_id=u.id WHERE ft.id=$id")->fetch_assoc();
$respuestas=$conn->query("SELECT fr.*,u.nombre usuario,u.rol FROM foro_respuestas fr LEFT JOIN usuarios u ON fr.usuario_id=u.id WHERE fr.tema_id=$id ORDER BY fr.fecha_creacion ASC");
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Foro</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body class="admin-body"><?php include __DIR__ . '/includes/topbar.php'; ?><div class="admin-container"><?php if(!$tema){ ?><div class="alert alert-danger">Tema no encontrado.</div><?php }else{ ?><div class="admin-card forum-topic"><span class="forum-category"><?php echo htmlspecialchars($tema['categoria']); ?></span><h2><?php echo htmlspecialchars($tema['titulo']); ?></h2><p><?php echo nl2br(htmlspecialchars($tema['mensaje'])); ?></p><small><?php echo htmlspecialchars($tema['empresa']??'General'); ?> · <?php echo htmlspecialchars($tema['usuario']??'Usuario'); ?> · <?php echo date('d/m/Y H:i',strtotime($tema['fecha_creacion'])); ?></small><?php if($rol=='superadmin'&&$tema['estado']!='cerrado'){ ?><form method="POST" class="mt-3"><button name="cerrar" class="btn btn-outline-success">Cerrar tema</button></form><?php } ?></div><h3 class="admin-title mt-4">Respuestas</h3><?php if($respuestas->num_rows==0){ ?><div class="admin-card"><p class="mb-0 text-muted">Todavía no hay respuestas.</p></div><?php } ?><?php while($r=$respuestas->fetch_assoc()){ ?><div class="admin-card mb-3 reply-card"><strong><?php echo htmlspecialchars($r['usuario']??'Usuario'); ?></strong><span><?php echo htmlspecialchars($r['rol']??''); ?> · <?php echo date('d/m/Y H:i',strtotime($r['fecha_creacion'])); ?></span><p><?php echo nl2br(htmlspecialchars($r['mensaje'])); ?></p></div><?php } ?><?php if($tema['estado']!='cerrado'){ ?><div class="admin-card mt-4"><h4>Responder</h4><form method="POST"><textarea name="mensaje" class="form-control mb-3" rows="4" required></textarea><button name="responder" class="btn btn-success">Enviar respuesta</button></form></div><?php }else{ ?><div class="alert alert-secondary mt-4">Este tema está cerrado.</div><?php } ?><?php } ?></div><?php include __DIR__ . '/includes/footer.php'; ?>
</body></html>
