<?php
session_start();
$conn = new mysqli('localhost', 'root', '', 'agroconnect');
$conn->set_charset('utf8mb4');
require_once 'agro_helper.php';
if (!isset($_SESSION['rol']) || $_SESSION['rol'] != 'jefe') { header('Location: login.php'); exit(); }
$empresa_id = intval($_SESSION['empresa_id'] ?? 0);
$empresaNombre = 'Sin empresa asignada';
$totalTrabajadores = $totalParcelas = $totalCultivos = $tareasPendientes = $tareasIncidencia = $tareasCompletadas = 0;
$ultimasTareas = null;
if ($empresa_id > 0) {
    $st = $conn->prepare('SELECT nombre FROM empresas WHERE id=?'); $st->bind_param('i', $empresa_id); $st->execute();
    $e = $st->get_result()->fetch_assoc(); if($e){ $empresaNombre = $e['nombre']; }
    $st2 = $conn->prepare("SELECT COUNT(*) AS total FROM usuarios WHERE empresa_id=? AND rol='trabajador'"); $st2->bind_param('i', $empresa_id); $st2->execute(); $totalTrabajadores = intval($st2->get_result()->fetch_assoc()['total'] ?? 0);
    if(agro_tabla_existe($conn,'parcelas')){ $p=$conn->prepare('SELECT COUNT(*) total FROM parcelas WHERE empresa_id=?'); $p->bind_param('i',$empresa_id); $p->execute(); $totalParcelas=intval($p->get_result()->fetch_assoc()['total']??0); }
    if(agro_tabla_existe($conn,'cultivos')){ $c=$conn->prepare('SELECT COUNT(*) total FROM cultivos WHERE empresa_id=?'); $c->bind_param('i',$empresa_id); $c->execute(); $totalCultivos=intval($c->get_result()->fetch_assoc()['total']??0); }
    if(agro_tabla_existe($conn,'tareas_agricolas') && agro_columna_existe($conn,'tareas_agricolas','trabajador_id')){
        $ts=$conn->prepare("SELECT estado, COUNT(*) total FROM tareas_agricolas WHERE empresa_id=? GROUP BY estado"); $ts->bind_param('i',$empresa_id); $ts->execute(); $rs=$ts->get_result();
        while($r=$rs->fetch_assoc()){ if($r['estado']==='pendiente')$tareasPendientes=intval($r['total']); if($r['estado']==='incidencia')$tareasIncidencia=intval($r['total']); if($r['estado']==='completada')$tareasCompletadas=intval($r['total']); }
        $ut=$conn->prepare("SELECT t.titulo,t.estado,t.fecha_limite,u.nombre trabajador,p.nombre parcela FROM tareas_agricolas t LEFT JOIN usuarios u ON t.trabajador_id=u.id LEFT JOIN parcelas p ON t.parcela_id=p.id WHERE t.empresa_id=? ORDER BY t.id DESC LIMIT 5"); $ut->bind_param('i',$empresa_id); $ut->execute(); $ultimasTareas=$ut->get_result();
    }
}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Panel Jefe - AgroConnect</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body class="admin-body">
<?php include __DIR__ . '/includes/topbar.php'; ?>
<div class="admin-container dashboard-container"><div class="dashboard-hero"><div><span class="eyebrow">Panel de jefe</span><h1><?php echo htmlspecialchars($empresaNombre); ?></h1><p>Bienvenido, <?php echo htmlspecialchars($_SESSION['nombre']); ?>. Gestiona trabajadores, parcelas, cultivos, tareas e incidencias de tu empresa.</p></div><div class="dashboard-actions"><a href="crear_trabajador.php" class="btn btn-success">Crear trabajador</a><a href="tareas.php" class="btn btn-outline-success">Asignar tareas</a><a href="grupos_trabajadores.php" class="btn btn-outline-success">Grupos</a><a href="incidencias.php" class="btn btn-outline-success">Incidencias</a><button type="button" id="notifyButton" class="btn btn-outline-success">Notificaciones</button></div></div>
<?php include 'tiempo_widget.php'; ?>
<section class="stats-grid mt-4"><div class="stat-card"><span>Trabajadores</span><strong><?php echo $totalTrabajadores; ?></strong><small>Usuarios activos de tu empresa</small></div><div class="stat-card"><span>Parcelas</span><strong><?php echo $totalParcelas; ?></strong><small>Explotaciones registradas</small></div><div class="stat-card"><span>Cultivos</span><strong><?php echo $totalCultivos; ?></strong><small>Producción controlada</small></div><div class="stat-card"><span>Tareas pendientes</span><strong><?php echo $tareasPendientes; ?></strong><small>Trabajos por realizar</small></div><div class="stat-card"><span>Incidencias tarea</span><strong><?php echo $tareasIncidencia; ?></strong><small>Necesitan atención</small></div><div class="stat-card"><span>Completadas</span><strong><?php echo $tareasCompletadas; ?></strong><small>Registradas en histórico</small></div></section>
<div class="admin-card mt-4"><h3>Últimas tareas asignadas</h3><?php if($ultimasTareas && $ultimasTareas->num_rows>0){ ?><div class="table-responsive"><table class="table"><thead><tr><th>Tarea</th><th>Trabajador</th><th>Parcela</th><th>Límite</th><th>Estado</th></tr></thead><tbody><?php while($t=$ultimasTareas->fetch_assoc()){ ?><tr><td><strong><?php echo htmlspecialchars($t['titulo']); ?></strong></td><td><?php echo htmlspecialchars($t['trabajador'] ?? ''); ?></td><td><?php echo htmlspecialchars($t['parcela'] ?? ''); ?></td><td><?php echo htmlspecialchars($t['fecha_limite'] ?: 'Sin límite'); ?></td><td><?php echo htmlspecialchars($t['estado']); ?></td></tr><?php } ?></tbody></table></div><?php } else { ?><p class="text-muted mb-0">Todavía no hay tareas asignadas.</p><?php } ?></div>
<section class="quick-grid mt-4"><a href="crear_trabajador.php" class="quick-card"><strong>Crear trabajadores</strong><span>Da de alta empleados solo en tu empresa.</span></a><a href="tareas.php" class="quick-card"><strong>Asignar tareas</strong><span>Planifica trabajos, asigna responsables y revisa estados.</span></a><a href="grupos_trabajadores.php" class="quick-card"><strong>Grupos de trabajadores</strong><span>Crea cuadrillas, turnos y equipos para asignar tareas en bloque.</span></a><a href="incidencias.php" class="quick-card"><strong>Incidencias</strong><span>Gestiona problemas de campo o soporte.</span></a><a href="foro.php" class="quick-card"><strong>Foro de empresas</strong><span>Pregunta dudas y consulta respuestas.</span></a><a href="parcelas.php" class="quick-card"><strong>Parcelas</strong><span>Registra ubicación, hectáreas y coordenadas.</span></a><a href="cultivos.php" class="quick-card"><strong>Cultivos</strong><span>Controla estado y clima por parcela.</span></a><a href="recursos.php" class="quick-card"><strong>Recursos</strong><span>Gestiona maquinaria, insumos y agua.</span></a><a href="mapa_parcelas.php" class="quick-card"><strong>Mapa agrícola</strong><span>Visualiza parcelas geolocalizadas, distancia y tiempo de cada zona.</span></a><a href="historico.php" class="quick-card"><strong>Histórico</strong><span>Consulta actividades realizadas.</span></a></section></div><script src="notificaciones.js"></script><?php include __DIR__ . '/includes/footer.php'; ?>
</body></html>
