<?php
session_start();
$conn = new mysqli("localhost", "root", "", "agroconnect");
$conn->set_charset("utf8mb4");
if (!isset($_SESSION['rol']) || $_SESSION['rol'] != 'superadmin') { header("Location: login.php"); exit(); }
function tablaExiste($conn, $tabla) { $tabla=$conn->real_escape_string($tabla); $res=$conn->query("SHOW TABLES LIKE '$tabla'"); return $res && $res->num_rows>0; }
function contar($conn, $sql) { $res=$conn->query($sql); if(!$res) return 0; return intval(($res->fetch_assoc())['total'] ?? 0); }
$totalEmpresas=contar($conn,"SELECT COUNT(*) AS total FROM empresas");
$totalUsuarios=contar($conn,"SELECT COUNT(*) AS total FROM usuarios");
$totalJefes=contar($conn,"SELECT COUNT(*) AS total FROM usuarios WHERE rol='jefe'");
$totalTrabajadores=contar($conn,"SELECT COUNT(*) AS total FROM usuarios WHERE rol='trabajador'");
$tieneIncidencias=tablaExiste($conn,'incidencias'); $tieneSesiones=tablaExiste($conn,'sesiones_activas'); $tieneForo=tablaExiste($conn,'foro_temas');
$incidenciasAbiertas=$tieneIncidencias?contar($conn,"SELECT COUNT(*) AS total FROM incidencias WHERE estado IN ('abierta','en_revision')"):0;
$incidenciasCriticas=$tieneIncidencias?contar($conn,"SELECT COUNT(*) AS total FROM incidencias WHERE prioridad='alta' AND estado <> 'resuelta'"):0;
$usuariosOnline=$tieneSesiones?contar($conn,"SELECT COUNT(*) AS total FROM sesiones_activas WHERE ultima_actividad >= (NOW() - INTERVAL 10 MINUTE)"):0;
$labels=[]; $datosIncidencias=[];
for($i=6;$i>=0;$i--){ $fecha=date('Y-m-d', strtotime("-$i days")); $labels[]=date('d/m', strtotime($fecha)); if($tieneIncidencias){ $stmt=$conn->prepare("SELECT COUNT(*) AS total FROM incidencias WHERE DATE(fecha_creacion)=?"); $stmt->bind_param("s",$fecha); $stmt->execute(); $datosIncidencias[]=intval($stmt->get_result()->fetch_assoc()['total']); } else {$datosIncidencias[]=0;} }
$ultimasIncidencias=$tieneIncidencias?$conn->query("SELECT i.*, e.nombre AS empresa FROM incidencias i LEFT JOIN empresas e ON i.empresa_id=e.id ORDER BY i.fecha_creacion DESC LIMIT 5"):false;
$ultimosTemas=$tieneForo?$conn->query("SELECT ft.*, e.nombre AS empresa, u.nombre AS usuario FROM foro_temas ft LEFT JOIN empresas e ON ft.empresa_id=e.id LEFT JOIN usuarios u ON ft.usuario_id=u.id ORDER BY ft.fecha_creacion DESC LIMIT 5"):false;
$conectados=$tieneSesiones?$conn->query("SELECT s.*, u.nombre, u.rol, e.nombre AS empresa FROM sesiones_activas s LEFT JOIN usuarios u ON s.usuario_id=u.id LEFT JOIN empresas e ON u.empresa_id=e.id WHERE s.ultima_actividad >= (NOW() - INTERVAL 10 MINUTE) ORDER BY s.ultima_actividad DESC LIMIT 8"):false;
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Panel SuperAdmin - AgroConnect</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style.css"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script></head><body class="admin-body">
<?php include __DIR__ . '/includes/topbar.php'; ?>
<div class="admin-container dashboard-container">
<div class="dashboard-hero"><div><span class="eyebrow">Panel de control</span><h1>Vista general del sistema</h1><p>Controla empresas, usuarios, incidencias, actividad reciente y comunicación entre empresas desde un único panel.</p></div><div class="dashboard-actions"><a href="empresas.php" class="btn btn-success">Gestionar empresas</a><a href="crear_jefe.php" class="btn btn-outline-success">Crear jefe</a><a href="usuarios.php" class="btn btn-outline-success">Ver usuarios</a><a href="foro.php" class="btn btn-outline-success">Foro</a><a href="parcelas.php" class="btn btn-outline-success">Gestión agrícola</a></div></div>
<?php if(!$tieneIncidencias || !$tieneSesiones || !$tieneForo){ ?><div class="alert alert-warning admin-alert">Importa primero <strong>actualizacion_superadmin.sql</strong> en phpMyAdmin para activar incidencias, usuarios conectados y foro.</div><?php } ?>
<?php include 'tiempo_widget.php'; ?>
<section class="stats-grid"><div class="stat-card"><span>Empresas</span><strong><?php echo $totalEmpresas; ?></strong><small>Registradas en la plataforma</small></div><div class="stat-card"><span>Usuarios</span><strong><?php echo $totalUsuarios; ?></strong><small><?php echo $totalJefes; ?> jefes · <?php echo $totalTrabajadores; ?> trabajadores</small></div><div class="stat-card"><span>Incidencias abiertas</span><strong><?php echo $incidenciasAbiertas; ?></strong><small><?php echo $incidenciasCriticas; ?> de prioridad alta</small></div><div class="stat-card"><span>Conectados ahora</span><strong><?php echo $usuariosOnline; ?></strong><small>Actividad en los últimos 10 min</small></div></section>
<div class="dashboard-grid"><div class="admin-card chart-card"><div class="section-title-row"><div><h3>Incidencias últimos 7 días</h3><p>Evolución diaria de incidencias creadas.</p></div><a href="incidencias.php" class="small-link">Ver todas</a></div><canvas id="incidenciasChart" height="120"></canvas></div><div class="admin-card"><div class="section-title-row"><div><h3>Usuarios conectados</h3><p>Sesiones activas recientes.</p></div></div><?php if($conectados && $conectados->num_rows>0){ ?><div class="activity-list"><?php while($c=$conectados->fetch_assoc()){ ?><div class="activity-item"><div><strong><?php echo htmlspecialchars($c['nombre'] ?? 'Usuario'); ?></strong><small><?php echo htmlspecialchars($c['empresa'] ?? 'Sin empresa'); ?> · <?php echo htmlspecialchars($c['rol'] ?? ''); ?></small></div><span class="status-dot">Online</span></div><?php } ?></div><?php } else { ?><p class="text-muted mb-0">No hay usuarios conectados ahora.</p><?php } ?></div></div>
<div class="dashboard-grid two-columns"><div class="admin-card"><div class="section-title-row"><div><h3>Últimas incidencias</h3><p>Problemas reportados por las empresas.</p></div><a href="incidencias.php" class="small-link">Gestionar</a></div><?php if($ultimasIncidencias && $ultimasIncidencias->num_rows>0){ ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Título</th><th>Empresa</th><th>Prioridad</th><th>Estado</th></tr></thead><tbody><?php while($i=$ultimasIncidencias->fetch_assoc()){ ?><tr><td><?php echo htmlspecialchars($i['titulo']); ?></td><td><?php echo htmlspecialchars($i['empresa'] ?? 'General'); ?></td><td><span class="badge bg-success"><?php echo htmlspecialchars($i['prioridad']); ?></span></td><td><?php echo htmlspecialchars($i['estado']); ?></td></tr><?php } ?></tbody></table></div><?php } else { ?><p class="text-muted mb-0">Todavía no hay incidencias registradas.</p><?php } ?></div>
<div class="admin-card"><div class="section-title-row"><div><h3>Foro de empresas</h3><p>Preguntas e incidencias compartidas.</p></div><a href="foro.php" class="small-link">Entrar</a></div><?php if($ultimosTemas && $ultimosTemas->num_rows>0){ ?><div class="activity-list"><?php while($t=$ultimosTemas->fetch_assoc()){ ?><a class="activity-item forum-preview" href="foro_tema.php?id=<?php echo $t['id']; ?>"><div><strong><?php echo htmlspecialchars($t['titulo']); ?></strong><small><?php echo htmlspecialchars($t['empresa'] ?? 'General'); ?> · <?php echo htmlspecialchars($t['usuario'] ?? 'Usuario'); ?></small></div><span><?php echo htmlspecialchars($t['estado']); ?></span></a><?php } ?></div><?php } else { ?><p class="text-muted mb-0">Todavía no hay temas en el foro.</p><?php } ?></div></div>
<section class="quick-grid"><a href="crear_jefe.php" class="quick-card"><strong>Crear jefes</strong><span>Alta de jefes y asignación a empresas.</span></a><a href="empresas.php" class="quick-card"><strong>Empresas</strong><span>Crear y revisar empresas registradas.</span></a><a href="usuarios.php" class="quick-card"><strong>Usuarios</strong><span>Consultar usuarios y roles del sistema.</span></a><a href="incidencias.php" class="quick-card"><strong>Incidencias</strong><span>Registrar, revisar y cerrar incidencias.</span></a><a href="foro.php" class="quick-card"><strong>Foro</strong><span>Comunicación entre empresas y soporte.</span></a><a href="parcelas.php" class="quick-card"><strong>Parcelas</strong><span>Vista de explotaciones por empresa.</span></a><a href="cultivos.php" class="quick-card"><strong>Cultivos</strong><span>Estado productivo y campañas.</span></a><a href="recursos.php" class="quick-card"><strong>Recursos</strong><span>Maquinaria, insumos, agua y personal.</span></a><a href="grupos_trabajadores.php" class="quick-card"><strong>Grupos de trabajadores</strong><span>Cuadrillas y equipos por empresa.</span></a><a href="tareas.php" class="quick-card"><strong>Tareas</strong><span>Planificación agrícola global.</span></a><a href="mapa_parcelas.php" class="quick-card"><strong>Mapa agrícola</strong><span>Visualiza parcelas geolocalizadas, distancia y tiempo de cada zona.</span></a><a href="historico.php" class="quick-card"><strong>Histórico</strong><span>Registro de actividades realizadas.</span></a></section></div>
<script>new Chart(document.getElementById('incidenciasChart'),{type:'line',data:{labels:<?php echo json_encode($labels); ?>,datasets:[{label:'Incidencias',data:<?php echo json_encode($datosIncidencias); ?>,tension:.35,fill:true,borderWidth:3}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});</script><script src="notificaciones.js"></script><?php include __DIR__ . '/includes/footer.php'; ?>
</body></html>
